# Site settings
author: Jay Sokolowski
title: Whiskey Neat Please
header-img: img/home-bg.png
email: jaysoko@gmail.com
copyright_name: Jay Sokolowski
description: > # this means to ignore newlines until "baseurl:"
  Whiskey Scraping/CLI
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  jaysoko

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
